services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DEV_DB_NAME}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
    - "5433:${PGPORT}"
  web:
    build: .
    command: /bin/sh -c "bin/rails db:create && bin/rails db:migrate && bin/rails server -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgresql #TODO: should be the same as service: postgresql and .env value
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${PGPORT}/${DEV_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PGPORT: ${PGPORT}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    user: "rails"
volumes:
  pgdata: