replicaCount: 1

image:
  repository: europe-west1-docker.pkg.dev/dev1/dev
  pullPolicy: IfNotPresent
  name: ruby-blog
  tag: 3.3.0

labels:
  app: web

namespace: default

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 128Mi

readinessProbe:
  path: /
  initialDelaySeconds: 10
  periodSeconds: 15
livenessProbe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 15

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

securityContext: 
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 2000
  allowPrivilegeEscalation: false
  privileged: false

psql:
  port: 5432
  host: postgresql-dev3.default.svc.cluster.local