apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
      - name: {{ .Values.labels.app }}
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.targetPort }}
            protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: psql
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psql
              key: POSTGRES_PASSWORD
        - name: DEV_DB_NAME
          valueFrom:
            secretKeyRef:
              name: psql
              key: DEV_DB_NAME
        - name: POSTGRES_HOST
          value: {{ .Values.psql.host }}
        - name: PGPORT
          value: "{{ .Values.psql.port }}"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: psql
              key: SECRET_KEY_BASE
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 15
