apiVersion: v1
kind: Service
metadata:
  name: {{ {{ .Chart.Name }} }}
  labels:
    app: {{ include "testday-web.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "testday-web.selectorLabels" . | nindent 4 }}
