replicaCount: 1

image:
  repository: europe-west1-docker.pkg.dev/dev1/dev
  pullPolicy: Always #TODO: to update the image each time due to absence of proper versioning
  name: ruby-on-rails-blog
  tag: latest

labels:
  app: ruby-on-rails-blog-web

namespace: dev1

service:
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 128Mi

readinessProbe:
  path: /
  initialDelaySeconds: 10
  periodSeconds: 15
livenessProbe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 15

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

securityContext: 
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 2000
  allowPrivilegeEscalation: false
  privileged: false

psql:
  port: 5432
  host: 10.100.64.3

ingress:
  enabled: true
  staticIPName: "ruby-blog-dev"
  hostname: "rails-blog.testing.dev"